# Generated by Django 3.2.5 on 2021-07-30 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_socialmedia_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='category',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
            preserve_default=False,
        ),
    ]
