# Generated by Django 3.2.5 on 2021-08-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210805_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='limit',
            field=models.IntegerField(default=10, verbose_name='Ограничение на количество скидок'),
        ),
    ]
