# Generated by Django 3.2.5 on 2021-08-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_operation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order_num'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='order_num',
            field=models.IntegerField(default=1, verbose_name='Фильтрация'),
            preserve_default=False,
        ),
    ]
