# Generated by Django 3.2.5 on 2021-08-06 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210806_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='deadline',
            new_name='coupon_duration',
        ),
        migrations.AddField(
            model_name='operation',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Заверешние купона'),
            preserve_default=False,
        ),
    ]
