# Generated by Django 3.2.5 on 2021-08-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210806_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
