# Generated by Django 3.2.5 on 2021-08-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_operation_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='end_date',
        ),
    ]
